# Python Practice Questions

### Question 1

Use an IPython built-in magic command to return the current working directory path

In [2]:
%pwd

'/Users/souminator'

### Question 2

Create a for loop to update the dictionary by_length which groups the words in the list word_samples by the length of words. The keys in by_length are the lengths of words.

In [20]:
word_samples = ['chalk', 'awk', 'pear', 'algebra', 'tie', 'nut', 'physics', 'magnolia', 'sycamore']
by_length = {}

In [21]:
for i in word_samples:
    by_length.setdefault(len(i),[]).append(i)
by_length
    

{5: ['chalk'],
 3: ['awk', 'tie', 'nut'],
 4: ['pear'],
 7: ['algebra', 'physics'],
 8: ['magnolia', 'sycamore']}

### Question 3

Use the map and lambda functions to create a list numbers_sq which contains the squared value of each element in the list numbers 

In [5]:
numbers = [1, 2, 3, 4]

In [9]:
numbers_sq = list(map(lambda x : x**2,numbers))
print (numbers_sq)

[1, 4, 9, 16]


### Question 4

Select every other element from list1 starting from the element with index = 1.

In [15]:
import numpy as np
np.random.seed(42)
list1 = np.random.randint(0,10,20)
list1

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5, 4, 1, 7, 5, 1])

In [24]:
for i in list1:
    print (i,end=",") ;
    

6,3,7,4,6,9,2,6,7,4,3,7,7,2,5,4,1,7,5,1,

### Question 5

Rename the columns 0, 1, and 2 in the Dataframe df0 to "apple", "banana", and "orange" respectively

In [25]:
import pandas as pd, numpy as np
np.random.seed(42)
df0 = pd.DataFrame(np.random.randint(low=0, high=5, size=(5, 3)))
df0

0  1  2
0  3  4  2
1  4  4  1
2  2  2  2
3  4  3  2
4  4  1  3

In [27]:
df0.columns = ["apple","banana","orange"]
print (df0)

   apple  banana  orange
0      3       4       2
1      4       4       1
2      2       2       2
3      4       3       2
4      4       1       3


In [31]:
#second method

df0.rename(columns = {'0':"apple",'1':"banana",'2':"orange"},inplace = True)
print (df0.columns)

Index(['apple', 'banana', 'orange'], dtype='object')


### Question 6

Identify names of columns in the Dataframe df1 which have missing values

In [32]:
import pandas as pd, numpy as np
sample_data = {'a': [5, 8, 2, 0], 'b': [7, 9, np.NaN, 1], 'c': [np.NaN, 3, 2, 8] }
df1 = pd.DataFrame(data = sample_data)
df1

a    b    c
0  5  7.0  NaN
1  8  9.0  3.0
2  2  NaN  2.0
3  0  1.0  8.0

In [39]:
df1.columns[df1.isnull().any()].tolist()

['b', 'c']

### Question 7

Select rows in the Dataframe df1 which have no missing values in both column b and c

In [53]:
import pandas as pd, numpy as np
sample_data = {'a': [5, 8, 2, 0], 'b': [7, 9, np.NaN, 1], 'c': [np.NaN, 3, 2, 8] }
df1 = pd.DataFrame(data = sample_data)
df1

a    b    c
0  5  7.0  NaN
1  8  9.0  3.0
2  2  NaN  2.0
3  0  1.0  8.0

In [71]:
df1.dropna(subset = ['b','c'])

a    b    c
1  8  9.0  3.0
3  0  1.0  8.0

### Question 8

Use the Dataframe df2 and calculate the average Sepal.Length and Sepal.Width of all the instances whose Species are versicolor or virginica

In [287]:
from pydataset import data
import pandas as pd
df2 = data('iris')
df2.head()
df3 = df2[['Sepal.Length','Sepal.Width','Species']]
df3.head(10)

Sepal.Length  Sepal.Width Species
1            5.1          3.5  setosa
2            4.9          3.0  setosa
3            4.7          3.2  setosa
4            4.6          3.1  setosa
5            5.0          3.6  setosa
6            5.4          3.9  setosa
7            4.6          3.4  setosa
8            5.0          3.4  setosa
9            4.4          2.9  setosa
10           4.9          3.1  setosa

In [289]:
arr = ['versicolor','virginica']
df3.loc[df3['Species'].isin(arr)].mean()

Sepal.Length    6.262
Sepal.Width     2.872
dtype: float64

### Question 9

For the Dataframe df3, return the names of columns whose data type is 'int64'

In [172]:
from pydataset import data
import pandas as pd
df3 = data('car90')
df3.head()

Country   Disp  Disp2  Eng.Rev  Front.Hd  Frt.Leg.Room  \
Acura Integra    Japan  112.0    1.8   2935.0       3.5          41.5   
Acura Legend     Japan  163.0    2.7   2505.0       2.0          41.5   
Audi 100       Germany  141.0    2.3   2775.0       2.5          41.5   
Audi 80        Germany  121.0    2.0   2835.0       4.0          42.0   
BMW 325i       Germany  152.0    2.5   2625.0       2.0          42.0   

               Frt.Shld  Gear.Ratio  Gear2     HP  ...  Steering  Tank  \
Acura Integra      53.0        3.26   3.21  130.0  ...     power  13.2   
Acura Legend       55.5        2.95   3.02  160.0  ...     power  18.0   
Audi 100           56.5        3.27   3.25  130.0  ...     power  21.1   
Audi 80            52.5        3.25   3.25  108.0  ...     power  15.9   
BMW 325i           52.0        3.02   2.99  168.0  ...     power  16.4   

                Tires  Trans1  Trans2 Turning     Type  Weight  Wheel.base  \
Acura Integra  195/60   man.5  auto.4    37.0    Small  2700.0         102   
Acura Legend   205/60   man.5  auto.4    42.0   Medium  3265.0         109   
Audi 100       205/60   man.5  auto.3    39.0   Medium  2935.0         106   
Audi 80        175/70   man.5  auto.3    35.0  Compact  2670.0         100   
BMW 325i       195/65   man.5  auto.4    35.0  Compact  2895.0         101   

               Width  
Acura Integra     67  
Acura Legend      69  
Audi 100          71  
Audi 80           67  
BMW 325i          65  

[5 rows x 34 columns]

In [223]:
df3.select_dtypes(include=['int64']).columns

Index(['Length', 'Luggage', 'Wheel.base', 'Width'], dtype='object')

### Question 10

1) Add a new column 'Size' to the Dataframe df3 which sums up the Height, Length, and Width for each row

2) Calculate the summary statistics of the column 'Size', e.g. count, mean, standard deviation, minimum, 1st quartile, median, 3rd quartile, and maximum

In [224]:
from pydataset import data
import pandas as pd
df3 = data('car90')
df3.head()

Country   Disp  Disp2  Eng.Rev  Front.Hd  Frt.Leg.Room  \
Acura Integra    Japan  112.0    1.8   2935.0       3.5          41.5   
Acura Legend     Japan  163.0    2.7   2505.0       2.0          41.5   
Audi 100       Germany  141.0    2.3   2775.0       2.5          41.5   
Audi 80        Germany  121.0    2.0   2835.0       4.0          42.0   
BMW 325i       Germany  152.0    2.5   2625.0       2.0          42.0   

               Frt.Shld  Gear.Ratio  Gear2     HP  ...  Steering  Tank  \
Acura Integra      53.0        3.26   3.21  130.0  ...     power  13.2   
Acura Legend       55.5        2.95   3.02  160.0  ...     power  18.0   
Audi 100           56.5        3.27   3.25  130.0  ...     power  21.1   
Audi 80            52.5        3.25   3.25  108.0  ...     power  15.9   
BMW 325i           52.0        3.02   2.99  168.0  ...     power  16.4   

                Tires  Trans1  Trans2 Turning     Type  Weight  Wheel.base  \
Acura Integra  195/60   man.5  auto.4    37.0    Small  2700.0         102   
Acura Legend   205/60   man.5  auto.4    42.0   Medium  3265.0         109   
Audi 100       205/60   man.5  auto.3    39.0   Medium  2935.0         106   
Audi 80        175/70   man.5  auto.3    35.0  Compact  2670.0         100   
BMW 325i       195/65   man.5  auto.4    35.0  Compact  2895.0         101   

               Width  
Acura Integra     67  
Acura Legend      69  
Audi 100          71  
Audi 80           67  
BMW 325i          65  

[5 rows x 34 columns]

In [228]:
df3['Size'] = df3.apply(lambda row: row['Height'] + row['Length']+ row['Width'], axis=1)
print (df3['Size'])

Acura Integra              291.5
Acura Legend               310.0
Audi 100                   315.5
Audi 80                    293.5
BMW 325i                   289.5
BMW 535i                   306.0
Buick Century              307.5
Buick Electra              319.5
Buick Le Sabre             320.0
Buick Regal                313.5
Buick Riviera              319.5
Cadillac Brougham          350.5
Cadillac De Ville          330.0
Cadillac Eldorado          312.0
Cadillac Seville           312.0
Chevrolet Astro            322.5
Chevrolet Beretta          304.0
Chevrolet Camaro           311.5
Chevrolet Caprice          339.5
Chevrolet Cavalier         295.0
Chevrolet Corsica          302.0
Chevrolet Corvette         291.5
Chevrolet Lumina           320.0
Chevrolet Lumina APV       328.0
Chrysler Imperial          323.0
Chrysler Le Baron          302.0
Chrysler Le Baron Coupe    303.0
Dodge Caravan              308.5
Dodge Colt                 275.0
Dodge Daytona              295.0
Dodge Dyna

In [229]:
print (df3['Size'].describe())

count    111.000000
mean     299.635135
std       18.774977
min      256.000000
25%      286.750000
50%      299.000000
75%      311.750000
max      351.000000
Name: Size, dtype: float64


### Question 11

Identify the row index label (i.e. the car model) for the car with the most weight in the Dataframe df3 

In [230]:
from pydataset import data
import pandas as pd
df3 = data('car90')
df3.head()

Country   Disp  Disp2  Eng.Rev  Front.Hd  Frt.Leg.Room  \
Acura Integra    Japan  112.0    1.8   2935.0       3.5          41.5   
Acura Legend     Japan  163.0    2.7   2505.0       2.0          41.5   
Audi 100       Germany  141.0    2.3   2775.0       2.5          41.5   
Audi 80        Germany  121.0    2.0   2835.0       4.0          42.0   
BMW 325i       Germany  152.0    2.5   2625.0       2.0          42.0   

               Frt.Shld  Gear.Ratio  Gear2     HP  ...  Steering  Tank  \
Acura Integra      53.0        3.26   3.21  130.0  ...     power  13.2   
Acura Legend       55.5        2.95   3.02  160.0  ...     power  18.0   
Audi 100           56.5        3.27   3.25  130.0  ...     power  21.1   
Audi 80            52.5        3.25   3.25  108.0  ...     power  15.9   
BMW 325i           52.0        3.02   2.99  168.0  ...     power  16.4   

                Tires  Trans1  Trans2 Turning     Type  Weight  Wheel.base  \
Acura Integra  195/60   man.5  auto.4    37.0    Small  2700.0         102   
Acura Legend   205/60   man.5  auto.4    42.0   Medium  3265.0         109   
Audi 100       205/60   man.5  auto.3    39.0   Medium  2935.0         106   
Audi 80        175/70   man.5  auto.3    35.0  Compact  2670.0         100   
BMW 325i       195/65   man.5  auto.4    35.0  Compact  2895.0         101   

               Width  
Acura Integra     67  
Acura Legend      69  
Audi 100          71  
Audi 80           67  
BMW 325i          65  

[5 rows x 34 columns]

In [247]:
df3['Weight'].idxmax()

'Cadillac Brougham'

### Question 12

Create a dictionary dict1 in which each key is an even number in list2 and each value is half of the corresponding key

In [248]:
import numpy as np
np.random.seed(42)
list2 = np.random.randint(0,100,20)
list2

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
       87, 29, 37])

In [299]:
dict1 = { i : i/2 for i in list2 if i%2 ==0}
print (dict1)

{92: 46.0, 14: 7.0, 60: 30.0, 20: 10.0, 82: 41.0, 86: 43.0, 74: 37.0, 2: 1.0, 52: 26.0}


### Question 13

Replace the missing values in the Dataframe df4 with the average value in each corresponding column

In [254]:
import pandas as pd, numpy as np
sample_data = {'Category': ['A', 'B', 'C', 'D'] * 2
               , 'Value1': [np.nan, 78, 82, 72, np.nan, 90, np.nan, 87]
               , 'Value2': [84, np.nan, 81, 74, 68, np.nan, np.nan, 91]
               , 'Value3': [83, 69, 73, 77, np.nan, 90, 89, 74]
              }
df4 = pd.DataFrame(data = sample_data)
df4

Category  Value1  Value2  Value3
0        A     NaN    84.0    83.0
1        B    78.0     NaN    69.0
2        C    82.0    81.0    73.0
3        D    72.0    74.0    77.0
4        A     NaN    68.0     NaN
5        B    90.0     NaN    90.0
6        C     NaN     NaN    89.0
7        D    87.0    91.0    74.0

In [263]:
df = df4.fillna(df4.mean())
df

Category  Value1  Value2     Value3
0        A    81.8    84.0  83.000000
1        B    78.0    79.6  69.000000
2        C    82.0    81.0  73.000000
3        D    72.0    74.0  77.000000
4        A    81.8    68.0  79.285714
5        B    90.0    79.6  90.000000
6        C    81.8    79.6  89.000000
7        D    87.0    91.0  74.000000

In [264]:
#check
df4['Value3'].mean()

79.28571428571428

### Question 14

Write a function named isPhoneNumber() to check whether a given string is a phone number with the same pattern as '919-684-2200'. Return True if the patterns match. Otherwise, return False.

In [271]:
import re
def isPhoneNumber(string):
    pattern = re.compile("^[\dA-Z]{3}-[\dA-Z]{3}-[\dA-Z]{4}$", re.IGNORECASE)
    return pattern.match(string) is not None

print (isPhoneNumber("919-684-2200"))
print (isPhoneNumber("919/684/2200"))
    

True
False


### Question 15

The copy() method is often used to create a copy of a list so that changing the values in the copy doesn't change the values in the original list (see the example as below).

In [272]:
import numpy as np
import copy
arr = np.arange(5)
arr_copy = copy.copy(arr)
arr_copy[0] = 100
print(arr)
print(arr_copy)

[0 1 2 3 4]
[100   1   2   3   4]


However, when the original list is a nested list, the copy() method doesn't function as expected, i.e. changing the values in the copy may change the values in the original list as well (see the example as below).

In [273]:
arr = [[100,200,300], 1, 2, 3, 4]
arr_copy = copy.copy(arr)
arr_copy[0][0] = 111
print(arr)
print(arr_copy)

[[111, 200, 300], 1, 2, 3, 4]
[[111, 200, 300], 1, 2, 3, 4]


Finish the following code and create a more *advanced* copy of the original list, so that the values in the original list won't change when we change the values in the copy.

In [277]:
arr = [[100,200,300], 1, 2, 3, 4]
arr_copy = copy.deepcopy(arr)
arr_copy[0][0] = 111
print(arr)
print(arr_copy)

[[100, 200, 300], 1, 2, 3, 4]
[[111, 200, 300], 1, 2, 3, 4]


## Non-Coding Questions

### Question 16

What's the main difference between the "==" and "is" operations?

In [ ]:
# "==" checks for equality, it checks whether the values are equal. "is" checks for identity, which means that
#it checks if the values are same in terms of being the same object in memory

### Question 17

What's the main difference between the append() and insert() list methods?

In [ ]:
#With append() we can just add a new entry at the end of a list, however with insert() we can add at any position. 

### Question 18

What's the main difference between the pass and continue statements?

In [ ]:
#pass statement does nothing and can be used to create a method which we don't want to implement
#continue skips the remaining statements in the loop and moves the control back to top of the loop

### Question 19

What's the main difference between a list and a dictionary?

In [ ]:
#list is an ordered set of objects which are accessed via their position
#dictionary is an unordered set which is accessed by keys

### Question 20

What's the return value of a call to a function which doesn't have a return statement?

In [ ]:
#the return value will be None